// Code generated by acp-go-generator; DO NOT EDIT.

package acp

// NewRequestPermissionOutcomeCancelled constructs a RequestPermissionOutcome using the 'cancelled' variant.
func NewRequestPermissionOutcomeCancelled() RequestPermissionOutcome {
	return RequestPermissionOutcome{Cancelled: &RequestPermissionOutcomeCancelled{Outcome: "cancelled"}}
}

// NewRequestPermissionOutcomeSelected constructs a RequestPermissionOutcome using the 'selected' variant.
func NewRequestPermissionOutcomeSelected() RequestPermissionOutcome {
	return RequestPermissionOutcome{Selected: &RequestPermissionOutcomeSelected{Outcome: "selected"}}
}

// NewSessionConfigOptionSelect constructs a SessionConfigOption using the 'select' variant.
func NewSessionConfigOptionSelect() SessionConfigOption {
	return SessionConfigOption{Select: &SessionConfigOptionSelect{Type: "select"}}
}
